@startuml

hide empty description

[*] -> Startup

Startup -> Detecting

state Charging {
ChargingPre -> ChargingFast
}

Detecting --> ChargingPre
Detecting --> ChargingFast
ChargingFast --> Detecting


Error : errorCode
ChargingPre --> Error
ChargingFast --> Error

Detecting --> Error

Startup --> Error
Error --> Startup





@enduml