name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install&cache
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi make
        version: 1.0

    - name: make
      run: make
